[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  PNPM_FLAGS = "--shamefully-hoist"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm dev"
  port = 3000
  publish = ".next"